GADGETS=alexwilliams.gspec  #littleBeatBox.gspec   test01.gspec test-trinket.gspec ledsnow.gspec door-message.gspec 

default: build-gadgets


include $(GADGETRON_ROOT)/Tools/AutomaKit/Gadgetron.make

